/* eslint-disable import/prefer-default-export */
import gqlService from '@modules/vendorbulktools/services/graphql';
import CategoryUpload from '@modules/vendorbulktools/pages/default/components/categoryUpload';
import BaseProductUpload from '@modules/vendorbulktools/pages/default/components/baseProductUpload';

export const bulkToolsOptions = [
    {
        name: 'Category Upload',
        code: 'category_upload',
        acl: 'oms_lite_vendor_product_upload_master',
        sample: 'vendor_category',
        activity: null,
        gqlUpload: gqlService.vendorCategoryUpload,
        component: <CategoryUpload />,
    },
    {
        name: 'Product Upload Master',
        code: 'product_upload_master',
        acl: 'oms_lite_vendor_product_upload_master',
        sample: 'vendor_product',
        activity: null,
        gqlUpload: gqlService.vendorProductUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Upload Configurable',
        code: 'product_upload_configurable',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_product_configurable',
        activity: null,
        gqlUpload: gqlService.vendorProductConfigurableUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Upload Bundle',
        code: 'product_upload_bundle',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_product_bundle',
        activity: null,
        gqlUpload: gqlService.vendorProductBundleUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Upload Grouped',
        code: 'product_upload_grouped',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_product_grouped',
        activity: null,
        gqlUpload: gqlService.vendorProductGroupedUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Upload Price',
        code: 'product_upload_price',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_product_configurable',
        activity: null,
        gqlUpload: gqlService.vendorProductPriceUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Upload Price By Location',
        code: 'product_upload_price_by_location',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_product_price_location',
        activity: null,
        gqlUpload: gqlService.vendorProductPriceLocationUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Image Upload',
        code: 'product_image_upload',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_product_image',
        activity: null,
        gqlUpload: gqlService.vendorProductPriceLocationUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Simplify Upload',
        code: 'product_simplify_upload',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_product_simplify',
        activity: null,
        gqlUpload: gqlService.vendorProductPriceLocationUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Assign Product Category Upload',
        code: 'assign_product_category_upload',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_category_assignation',
        activity: null,
        gqlUpload: gqlService.vendorProductPriceLocationUpload,
        component: <BaseProductUpload />,
    },
];
